// The active plan: name, owner, period, scope, assumptions and VERSION. Saving freezes a version; an approved plan returns to draft when it changes.
// Plans live apart from actual data and from the unapproved targets: editing a plan or its scenario never changes either.
import React, { useState } from 'react';
import { useAr } from '../../utils/useAr';
import { fmtMoney } from '../../utils/money';
import { PLAN_STATUS, newPlan, saveVersion, patchPlan, editPlan, approvePlan, unsavedChanges, DEFAULT_PLAN_SCOPE, scopeLabelOf } from '../../data/planStore';
import { amanahOptionsOf, REVENUE_SOURCES, REVENUE_SOURCE_KEYS } from '../../data/revenueLedger';
import { DateRangeFields } from '../revenue/RevenueUI';
import { fmtRiyadh } from '../../data/clock';
import { actorName } from '../../utils/actor';

export default function PlanBar({ store, setStore, plan, summary, versionContext, canEdit, user, onOpenDashboard, today }) {
  const { L, B, ar, lang } = useAr();
  const by = actorName(user, lang) || L('مستخدم', 'user');
  const [showVers, setShowVers] = useState(false); const [showHist, setShowHist] = useState(false); const [naming, setNaming] = useState(null);
  const sc = { ...DEFAULT_PLAN_SCOPE, ...(plan.scope || {}) };
  const setScope = (patch) => setPlan((p) => { const next = { ...DEFAULT_PLAN_SCOPE, ...(p.scope || {}), ...patch }; return editPlan(p, { scope: { ...next, label: scopeLabelOf(next, ar) } }, by); });
  const maxEnd = `${Number(today.slice(0, 4)) + 1}-12-31`;
  const setPlan = (fn) => setStore((s) => ({ ...s, plans: s.plans.map((p) => (p.id === plan.id ? fn(p) : p)) }));
  const lock = !canEdit; const lt = lock ? L('يتطلب صلاحية المراجعة', 'Requires review permission') : '';
  const create = (name) => { const nm = (name || '').trim(); if (!nm) return; const p = newPlan({ by, name: nm, scope: { ...DEFAULT_PLAN_SCOPE, label: scopeLabelOf(DEFAULT_PLAN_SCOPE, ar) }, period: { from: `${today.slice(0, 4)}-01-01`, to: `${today.slice(0, 4)}-12-31` } }); setStore((st) => ({ ...st, plans: [p, ...st.plans], activeId: p.id })); setNaming(null); };
  return (
    <div className="card st-card" role="region" aria-label={L('الخطة', 'Plan')}>
      <div className="st-grid" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(210px, 1fr))' }}>
        <div className="st-field"><label htmlFor="pl-sel">{L('الخطة', 'Plan')}</label><select id="pl-sel" className="select" value={plan.id} onChange={(e) => setStore((s) => ({ ...s, activeId: e.target.value }))}>{store.plans.map((p) => <option key={p.id} value={p.id}>{p.name} · v{p.version}</option>)}</select></div>
        <div className="st-field"><label htmlFor="pl-name">{L('اسم الخطة', 'Plan name')}</label><input id="pl-name" className="input" value={plan.name} disabled={lock} title={lt} onChange={(e) => setPlan((p) => editPlan(p, { name: e.target.value }, by))} /></div>
        <div className="st-field"><label htmlFor="pl-own">{L('مالك الخطة', 'Plan owner')}</label><input id="pl-own" className="input" value={plan.owner || ''} placeholder={L('غير مسند', 'unassigned')} disabled={lock} title={lt} onChange={(e) => setPlan((p) => editPlan(p, { owner: e.target.value }, by))} /></div>
        <div className="st-field"><label>{L('فترة الخطة', 'Plan period')}</label>{lock ? <bdi dir="ltr">{plan.period.from} → {plan.period.to}</bdi> : <DateRangeFields from={plan.period.from} to={plan.period.to} today={maxEnd} planMax={maxEnd} lang={lang} idPrefix="plan" hint={L(`الأرقام تُحسب حتى ${plan.period.to < today ? plan.period.to : today} (لا معاملات فعلية بعد اليوم)`, `Figures are computed up to ${plan.period.to < today ? plan.period.to : today} (no actual transactions after today)`)} onChange={(r) => { if (r) setPlan((p) => editPlan(p, { period: { from: r.from, to: r.to } }, by)); }} />}</div>
        <div className="st-field"><label htmlFor="pl-am">{L('الأمانة', 'Amanah')}</label><select id="pl-am" className="select" disabled={lock} title={lt} value={Array.isArray(sc.amanah) ? 'all' : sc.amanah} onChange={(e) => setScope({ amanah: e.target.value, muni: 'all' })}><option value="all">{L('كل الأمانات', 'All Amanahs')}</option>{amanahOptionsOf().map((a) => <option key={a.key} value={a.key}>{ar ? a.ar : a.en}</option>)}</select></div>
        <div className="st-field"><label htmlFor="pl-src">{L('مصدر الإيراد', 'Revenue source')}</label><select id="pl-src" className="select" disabled={lock} title={lt} value={sc.source} onChange={(e) => setScope({ source: e.target.value })}><option value="all">{L('كل المصادر', 'All sources')}</option>{REVENUE_SOURCE_KEYS.map((k) => <option key={k} value={k}>{ar ? REVENUE_SOURCES[k].ar : REVENUE_SOURCES[k].en}</option>)}</select></div>
        <div className="st-field"><label>{L('الإصدار والحالة', 'Version and status')}</label><div><b>{plan.version ? `v${plan.version}` : L('غير محفوظ', 'unsaved')}</b> <span className={`st-tag ${plan.status === 'approved' ? 'st-tag--actual' : 'st-tag--warn'}`}>{B(PLAN_STATUS[plan.status])}{plan.approvedBy ? ` — ${plan.approvedBy}` : ''}</span>{unsavedChanges(plan) && <span className="st-tag st-tag--warn" role="status">{L('تعديلات غير محفوظة في إصدار', 'Changes not saved as a version')}</span>}</div></div>
      </div>
      <div className="st-field"><label htmlFor="pl-as">{L('افتراضات الخطة', 'Plan assumptions')}</label><textarea id="pl-as" className="input" rows={2} disabled={lock} title={lt} value={plan.assumptions} placeholder={L('اكتب الافتراضات الأساسية للخطة (مصدرها، حدودها).', 'Write the plan’s key assumptions (source, limits).')} onChange={(e) => setPlan((p) => editPlan(p, { assumptions: e.target.value }, by))} /></div>
      <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', alignItems: 'center' }}>
        <button type="button" className="btn btn-sm btn-primary" disabled={lock} title={lt} onClick={() => setPlan((p) => saveVersion(patchPlan({ ...p, owner: (p.owner || '').trim() || null }, {}, by), { by, summary, context: versionContext }))}>{L('حفظ كإصدار جديد', 'Save as a new version')}</button>
        <button type="button" className="btn btn-sm" disabled={lock || plan.status === 'approved' || !plan.version} title={lock ? lt : !plan.version ? L('احفظ إصداراً أولاً', 'Save a version first') : ''} onClick={() => setPlan((p) => approvePlan(p, by))}>{L('اعتماد الخطة', 'Approve the plan')}</button>
        {naming === null ? <button type="button" className="btn btn-sm btn-ghost" onClick={() => setNaming(L(`خطة ${today.slice(0, 4)} — جديدة`, `Plan ${today.slice(0, 4)} — new`))} disabled={lock} title={lt}>＋ {L('خطة جديدة', 'New plan')}</button> : <span style={{ display: 'inline-flex', gap: 6, alignItems: 'center' }}><input id="pl-new" className="input" aria-label={L('اسم الخطة الجديدة', 'New plan name')} value={naming} onChange={(e) => setNaming(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') create(naming); if (e.key === 'Escape') setNaming(null); }} style={{ width: 200 }} /><button type="button" className="btn btn-sm btn-primary" onClick={() => create(naming)}>{L('إنشاء', 'Create')}</button><button type="button" className="btn btn-sm btn-ghost" onClick={() => setNaming(null)}>{L('إلغاء', 'Cancel')}</button></span>}
        <button type="button" className="btn btn-sm btn-ghost" onClick={() => onOpenDashboard(plan)}>{L('فتح فترة الخطة ونطاقها في لوحة المعلومات', 'Open the plan period and scope in the dashboard')}</button>
        <button type="button" className="btn btn-sm btn-ghost" aria-expanded={showVers} onClick={() => setShowVers((v) => !v)}>{L(`الإصدارات (${plan.versions.length})`, `Versions (${plan.versions.length})`)}</button>
        <button type="button" className="btn btn-sm btn-ghost" aria-expanded={showHist} onClick={() => setShowHist((v) => !v)}>{L('سجل التغييرات', 'Change history')}</button>
      </div>
      <div className="muted" style={{ fontSize: 12 }}>{L('اعتماد الخطة يخص افتراضاتها فقط؛ لا يجعل أي مستهدف معتمداً ولا يغيّر أي بيانات فعلية.', 'Approving a plan concerns its assumptions only; it does not make any target approved and changes no actual data.')}</div>
      {showVers && (plan.versions.length ? <div className="st-table-wrap"><table className="table"><thead><tr><th>{L('الإصدار', 'Version')}</th><th>{L('التاريخ', 'Date')}</th><th>{L('بواسطة', 'By')}</th><th>{L('نسبة التحصيل (سيناريو)', 'Rate (scenario)')}</th><th>{L('المحصّل (سيناريو)', 'Collected (scenario)')}</th><th>{L('الميزان التمويلي المتوقع', 'Projected funding balance')}</th><th>{L('سياق الاحتساب المحفوظ', 'Stored calculation context')}</th><th /></tr></thead><tbody>{plan.versions.map((v) => <tr key={v.version}><td>v{v.version}</td><td dir="ltr">{fmtRiyadh(v.at)}</td><td>{v.by}</td><td dir="ltr">{v.summary?.rate != null ? `${(v.summary.rate * 100).toFixed(1)}%` : '—'}</td><td dir="ltr">{v.summary?.collected != null ? fmtMoney(v.summary.collected, { lang }) : '—'}</td><td dir="ltr">{v.summary?.balance != null ? fmtMoney(v.summary.balance, { lang }) : L('غير متاح', 'n/a')}</td><td style={{ fontSize: 12 }}>{v.context ? <><bdi dir="ltr">{v.context.period.from} → {v.context.period.to}</bdi> · {v.context.scope?.label || scopeLabelOf(v.context.scope, ar)} · {v.context.basis === 'periodEnd' ? L('التحصيل حتى نهاية الفترة', 'collections to period end') : L('التحصيل حتى اليوم', 'collections to today')} · {L('قطع البيانات', 'data cut-off')} <bdi dir="ltr">{v.context.cutoff}</bdi>{(v.context.cutoff !== versionContext.cutoff || v.context.config !== versionContext.config) && <div><span className="st-tag st-tag--warn">{v.context.cutoff !== versionContext.cutoff ? L('تغيّرت البيانات منذ الحفظ', 'Data has changed since this version was saved') : L('تغيّر الإعداد منذ الحفظ', 'The configuration has changed since this version was saved')}</span></div>}</> : <span className="muted">{L('إصدار قديم: لم يُحفظ فيه سياق الاحتساب', 'Older version: no calculation context was stored')}</span>}</td><td><button type="button" className="btn btn-sm btn-ghost" disabled={lock} onClick={() => setPlan((p) => editPlan(p, { scenario: { ...v.scenario }, planDate: v.planDate, assumptions: v.assumptions }, by))}>{L('استعادة كمسودة', 'Restore as draft')}</button></td></tr>)}</tbody></table></div> : <div className="muted" style={{ fontSize: 12.5 }}>{L('لا إصدارات محفوظة بعد.', 'No saved versions yet.')}</div>)}
      {showHist && <ul className="res__list res__list--plain" style={{ fontSize: 12 }}>{plan.history.slice(0, 30).map((h, i) => <li key={i}>{fmtRiyadh(h.at)} · {h.by} · {h.change} {h.note}</li>)}</ul>}
    </div>
  );
}
